### ISSUE TITLE
Double quotes used all across the repo

### ISSUE THREAD

**Issue by balthazar** [meriadec/webusb-mac-chrome-91#1]
What is this blasphemy? Please fix asap.

**Comment by meriadec** [comment]
oh, not really my code, was an extract from https://codesandbox.io/s/ydx4v in order to deploy it on static page :doge:
however, i disagree, best configuration is no configuration, and double quotes are the prettier default :stuck_out_tongue_winking_eye: (prettier is a code formatting tool, more infos there https://prettier.io/)

Have a good day, and happy hacking!
